	MACRO	_SetBaud
	call	uart_evo_rs232.SetBaud
	ENDM

	MACRO	_SetLineControl
	call 	uart_evo_rs232.SetLineControl
	ENDM

	MACRO	_SendChar
	call	uart_evo_rs232.PutChar
	ENDM

	MACRO	_ReceveChar
	call	uart_evo_rs232.GetChar
	ENDM

	MACRO	_Read
	call	uart_evo_rs232.Read
	ENDM

	MACRO	_Write
	call	uart_evo_rs232.Read
	ENDM

	MACRO	_HaveRXData
	call	uart_evo_rs232.DRStatus
	ENDM

	MACRO	_Check_RX_Owerflow
	call	uart_evo_rs232.OEStatus
	ENDM

	MACRO	_init_uart
 	call	uart_evo_rs232.Init
	ENDM