;TODO
        MACRO	_getkey
	CALL	keys.get_key	
	ENDM

        MACRO	_waitkey
	CALL	keys.wait_key	
	ENDM

        MACRO	_waitkeyoff
	CALL	keys.wait_keyoff
	ENDM

        MACRO	_is_enter_key
	CALL	keys.is_enter_key
	ENDM

        MACRO	_is_escape_key
	CALL	keys.is_escape_key
	ENDM

        MACRO	_is_backspace_key
	CALL	keys.is_backspace_key
	ENDM

        MACRO	_is_del_key
	CALL	keys.is_del_key
	ENDM

        MACRO	_is_ins_key
	CALL	keys.is_ins_key
	ENDM
