	MODULE wind_macros

	MACRO	_printw descr
	LD	HL, descr
	CALL	wind.PRINTW
	ENDM

	MACRO	_prints string
        LD      HL,string
        CALL    wind.PRINTS
	ENDM

	MACRO	_endw
	CALL	wind.ENDW
	ENDM

	MACRO	_closew
	CALL	wind.ENDW
	ENDM

	MACRO	_cur_on
	call	wind.CUR_ON
	ENDM

	MACRO	_cur_off
	call	wind.CUR_OFF
	ENDM

	MACRO	_inp_str bufer
	LD	HL, bufer
	CALL	wind.INP_STR
	ENDM

	MACRO	_printc
	CALL	wind.PRINTC
	ENDM

	MACRO	_clearwindow
	LD	A,31
	CALL	wind.PRINTC
	ENDM

	ENDMODULE

