;--- JZ (JP Z) MACROS ----------------------------------------------------------------------
        MACRO   JZ addr
        JP      Z,addr
        ENDM
;----JNZ (JP NZ) MACROS---------------------------------------------------------------------
        MACRO   JNZ addr
        JP      NZ, addr
        ENDM
;----JRNZ (JR NZ) MACROS---------------------------------------------------------------------
        MACRO   JRNZ addr
        JR      NZ, addr
        ENDM
;----JRZ (JR Z) MACROS---------------------------------------------------------------------
        MACRO   JRZ addr
        JR      Z, addr
        ENDM

